CRITICAL - 2023-10-23 23:44:57 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-10-23 23:44:57 --> Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\codeigniter\system\Helpers\number_helper.php:136
Stack trace:
#0 C:\xampp\htdocs\codeigniter\system\Helpers\number_helper.php(55): format_number(6, 2, NULL, Array)
#1 C:\xampp\htdocs\codeigniter\system\Debug\BaseExceptionHandler.php(145): number_to_size(6, 2)
#2 C:\xampp\htdocs\codeigniter\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 C:\xampp\htdocs\codeigniter\system\Debug\BaseExceptionHandler.php(241): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 C:\xampp\htdocs\codeigniter\system\Debug\ExceptionHandler.php(112): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\codeigniter\system\Debug\Exceptions.php(149): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\codeigniter\system\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\codeigniter\system\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-23 23:47:35 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-10-23 23:47:35 --> Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\codeigniter\system\Helpers\number_helper.php:136
Stack trace:
#0 C:\xampp\htdocs\codeigniter\system\Helpers\number_helper.php(55): format_number(6, 2, NULL, Array)
#1 C:\xampp\htdocs\codeigniter\system\Debug\BaseExceptionHandler.php(145): number_to_size(6, 2)
#2 C:\xampp\htdocs\codeigniter\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 C:\xampp\htdocs\codeigniter\system\Debug\BaseExceptionHandler.php(241): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\codeigniter\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 C:\xampp\htdocs\codeigniter\system\Debug\ExceptionHandler.php(112): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\codeigniter\system\Debug\Exceptions.php(149): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\codeigniter\system\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\codeigniter\system\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\codeigniter\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-23 21:55:03 --> Config\App::$baseURL is invalid.
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 SYSTEMPATH\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 2 SYSTEMPATH\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 3 SYSTEMPATH\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
 5 SYSTEMPATH\Config\Services.php(799): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 8 SYSTEMPATH\Config\Services.php(792): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
10 SYSTEMPATH\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', [])
11 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
12 SYSTEMPATH\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(655): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-23 21:55:03 --> Uncaught CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL is invalid. in C:\xampp\htdocs\codeigniter\system\HTTP\SiteURI.php:199
Stack trace:
#0 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\codeigniter\system\Config\Services.php(799): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\codeigniter\system\Config\Services.php(792): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\codeigniter\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\codeigniter\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\codeigniter\system\Config\Services.php(520): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\codeigniter\system\Debug\Exceptions.php(137): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\ConfigException))
#18 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\ConfigException
Config\App::$baseURL is invalid.
#0 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\codeigniter\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\codeigniter\system\Config\Services.php(799): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\codeigniter\system\Config\Services.php(792): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\codeigniter\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\codeigniter\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\codeigniter\system\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\codeigniter\system\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\codeigniter\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\codeigniter\system\CodeIgniter.php(655): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\codeigniter\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\codeigniter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
